sudo: required
services:
  - docker
language: go
go:
  - stable
script: make test
before_deploy:
  - go get -v github.com/mitchellh/gox
  - gox
      -os="linux darwin windows"
      -arch="386 amd64"
      -output "pkg/{{.Dir}}_{{.OS}}_{{.Arch}}"
      -ldflags="-X main.Version=`git describe --tags --match 'v*'`"
  - ./pkg/gst_linux_amd64 --version # Verify compiled binaries
deploy: # Deploy stable version if commmits have a tag such as 'v2.0.0'
  provider: releases
  api_key: $GITHUB_TOKEN
  overwrite: true
  file_glob: true
  file: "pkg/*"
  skip_cleanup: true
  on:
    tags: true
