[[constraint]]
  name = "github.com/Songmu/prompter"
  version = "0.1.0"

[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/daviddengcn/go-colortext"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/motemen/go-gitconfig"

[[constraint]]
  branch = "master"
  name = "github.com/andreyvit/diff"

[prune]
  go-tests = true
  unused-packages = true