#!/bin/bash
set -e

echo "Generating CHANGELOG.md ..."

gem install github_changelog_generator
github_changelog_generator -t $GITHUB_TOKEN $TRAVIS_REPO_SLUG

remote="https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git"
git checkout $TRAVIS_BRANCH
git config user.email "support@travis-ci.org"
git config user.name "travisbot"
git add -A
git commit -m "[ci skip] Update CHANGELOG $TRAVIS_BUILD_ID"

git push $remote $TRAVIS_BRANCH

if [[ $? -ne 0 ]]; then
  echo "Failed push to Github"
  exit 1
else
  echo "Pushed to Github"
fi
